name: Docker

on:
  schedule:
    - cron: '23 4 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ] # Tags as releases
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2.4.1
        
      - uses: docker/metadata-action@v4.3.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚀 Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # don't push on PRs
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
